package worldguesser;

import java.util.Map;

public class CountryList {

    public static final Map<String, String> countriesById = Map.ofEntries(
        Map.entry("gl", "Denmark"),
        Map.entry("dk", "Denmark"),
        Map.entry("fo", "Denmark"),
        Map.entry("is", "Iceland"),
        Map.entry("no", "Norway"),
        Map.entry("se", "Sweden"),
        Map.entry("fi", "Finland"),
        Map.entry("gb-gbn", "United Kingdom"),
        Map.entry("path1207", "United Kingdom"),
        Map.entry("gb-nir", "United Kingdom"),
        Map.entry("im", "United Kingdom"),
        Map.entry("ie", "Ireland"),
        Map.entry("path5848", "Netherlands"),
        Map.entry("be", "Belgium"),
        Map.entry("cz", "Czechia"),
        Map.entry("ee", "Estonia"),
        Map.entry("lv", "Latvia"),
        Map.entry("lt", "Lithuania"),
        Map.entry("by", "Belarus"),
        Map.entry("ru-main", "Russia"),
        Map.entry("ru-kgd", "Russia"),
        Map.entry("pl", "Poland"),
        Map.entry("path3849", "Ukraine"),
        Map.entry("path3950", "Moldova"),
        Map.entry("ro", "Romania"),
        Map.entry("bg", "Bulgaria"),
        Map.entry("rs", "Serbia"),
        Map.entry("hu", "Hungary"),
        Map.entry("sk", "Slovakia"),
        Map.entry("at", "Austria"),
        Map.entry("ch", "Switzerland"),
        Map.entry("it", "Italy"),
        Map.entry("si", "Slovenia"),
        Map.entry("hr", "Croatia"),
        Map.entry("ba", "Bosnia and Herzegovina"),
        Map.entry("me", "Montenegro"),
        Map.entry("al", "Albania"),
        Map.entry("xk", "Serbia"),
        Map.entry("mk", "North Macedonia"),
        Map.entry("gr", "Greece"),
        Map.entry("tr", "Türkiye"),
        Map.entry("es", "Spain"),
        Map.entry("pt", "Portugal"),
        Map.entry("nc", "Cyprus"),
        Map.entry("de", "Germany"),
        Map.entry("fr", "France"),
        Map.entry("path5742", "Luxembourg"),
        Map.entry("mt", "Malta"),
        Map.entry("ad", "Andorra"),
        Map.entry("li", "Liechtenstein"),
        Map.entry("sm", "San Marino"),
        Map.entry("va", "Vatican City"),
        Map.entry("mc", "Monaco")
    );
}